In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("global_cybersecurity.csv")

In [3]:
df.head()

,Country,Year,Attack Type,Target Industry,Financial Loss (in Million $),Number of Affected Users,Attack Source,Security Vulnerability Type,Defense Mechanism Used,Incident Resolution Time (in Hours)
0,China,2019,Phishing,Education,80.53,773169,Hacker Group,Unpatched Software,VPN,63
1,China,2019,Ransomware,Retail,62.19,295961,Hacker Group,Unpatched Software,Firewall,71
2,India,2017,Man-in-the-Middle,IT,38.65,605895,Hacker Group,Weak Passwords,VPN,20
3,UK,2024,Ransomware,Telecommunications,41.44,659320,Nation-state,Social Engineering,AI-based Detection,7
4,Germany,2018,Man-in-the-Middle,IT,74.41,810682,Insider,Social Engineering,VPN,68

In [4]:
df.columns

Index(['Country', 'Year', 'Attack Type', 'Target Industry',
       'Financial Loss (in Million $)', 'Number of Affected Users',
       'Attack Source', 'Security Vulnerability Type',
       'Defense Mechanism Used', 'Incident Resolution Time (in Hours)'],
      dtype='object')

In [5]:
df = df.rename(columns={
        'Country': 'country',
        'Year': 'year',
        'Attack Type': 'attack_type',
        'Target Industry': 'industry',
        'Financial Loss (in Million $)': 'financial_loss_millions',
        'Number of Affected Users': 'affected_users',
        'Attack Source': 'attack_source',
        'Security Vulnerability Type': 'vulnerability_type',
        'Defense Mechanism Used': 'defense_mechanism',
        'Incident Resolution Time (in Hours)': 'resolution_hours'
    })

In [6]:
df.columns

Index(['country', 'year', 'attack_type', 'industry', 'financial_loss_millions',
       'affected_users', 'attack_source', 'vulnerability_type',
       'defense_mechanism', 'resolution_hours'],
      dtype='object')

In [13]:
df.isnull().sum()

country                    0
year                       0
attack_type                0
industry                   0
financial_loss_millions    0
affected_users             0
attack_source              0
vulnerability_type         0
defense_mechanism          0
resolution_hours           0
dtype: int64

In [15]:
df['year'] = pd.to_datetime(df['year'], format='%Y')

In [17]:
df.drop_duplicates(inplace=True)

In [19]:
df.shape

(3000, 10)

In [21]:
df['financial_loss_millions'] = pd.to_numeric(df['financial_loss_millions'], errors='coerce')
df['affected_users'] = pd.to_numeric(df['affected_users'], errors='coerce')
df['resolution_hours'] = pd.to_numeric(df['resolution_hours'], errors='coerce')

In [23]:
df.to_csv("cyberthreat_clean.csv")

In [25]:
df.head(20)

,country,year,attack_type,industry,financial_loss_millions,affected_users,attack_source,vulnerability_type,defense_mechanism,resolution_hours
0,China,2019-01-01,Phishing,Education,80.53,773169,Hacker Group,Unpatched Software,VPN,63
1,China,2019-01-01,Ransomware,Retail,62.19,295961,Hacker Group,Unpatched Software,Firewall,71
2,India,2017-01-01,Man-in-the-Middle,IT,38.65,605895,Hacker Group,Weak Passwords,VPN,20
3,UK,2024-01-01,Ransomware,Telecommunications,41.44,659320,Nation-state,Social Engineering,AI-based Detection,7
4,Germany,2018-01-01,Man-in-the-Middle,IT,74.41,810682,Insider,Social Engineering,VPN,68
5,Germany,2017-01-01,Man-in-the-Middle,Retail,98.24,285201,Unknown,Social Engineering,Antivirus,25
6,Germany,2016-01-01,DDoS,Telecommunications,33.26,431262,Insider,Unpatched Software,VPN,34
7,France,2018-01-01,SQL Injection,Government,59.23,909991,Unknown,Social Engineering,Antivirus,66
8,India,2016-01-01,Man-in-the-Middle,Banking,16.88,698249,Unknown,Social Engineering,VPN,47
9,UK,2023-01-01,DDoS,Healthcare,69.14,685927,Hacker Group,Unpatched Software,Firewall,58
10,China,2019-01-01,Phishing,Telecommunications,88.67,493675,Unknown,Zero-day,VPN,29
11,China,2016-01-01,SQL Injection,Healthcare,38.81,920768,Hacker Group,Unpatched Software,AI-based Detection,27
12,India,2019-01-01,Ransomware,Education,30.56,583204,Insider,Zero-day,Firewall,37
13,France,2023-01-01,DDoS,Healthcare,58.37,599797,Nation-state,Unpatched Software,AI-based Detection,35
14,France,2024-01-01,DDoS,IT,48.01,922258,Unknown,Social Engineering,Encryption,64
15,Australia,2022-01-01,Phishing,Banking,64.31,120789,Nation-state,Zero-day,Encryption,36
16,Russia,2017-01-01,Man-in-the-Middle,Healthcare,13.04,850158,Hacker Group,Unpatched Software,AI-based Detection,67
17,India,2015-01-01,DDoS,IT,93.14,805278,Insider,Social Engineering,Encryption,56
18,UK,2019-01-01,Malware,Telecommunications,14.01,578443,Insider,Social Engineering,Firewall,28
19,India,2016-01-01,DDoS,IT,36.45,261808,Nation-state,Social Engineering,AI-based Detection,6